version: 0.2

env:
  parameter-store:
    CLIENTID=AUTH0_RULE_DEPLOY_CLIENTID
    CLIENTSECRET=AUTH0_RULE_DEPLOY_CLIENTSECRET
    URI=AUTH0_URI
phases:
  build:
    commands:
      - make install
  post_build:
    commands:
      - make CLIENTID=$(CLIENTID) CLIENTSECRET=$(CLIENTSECRET) URI=$(URI) deploy
